### ISSUE TITLE
Add CUDA device support to the docker container

### ISSUE THREAD

**Issue by sjperkins** [radio-astro/docker-images#15]
It seems like its possible to expose GPU devices to processes within docker. See [here](https://github.com/dotcloud/docker/issues/682) and [here](http://qiita.com/syoyo/items/07d59b526a7d31e83824) for example.

I don't particularly require this feature, but I thought I'd log it in case you think baking CUDA packages into the papino container is a good idea.

**Comment by gijzelaerr** [comment]
NVidia has a sort of workaround for this now

https://github.com/NVIDIA/nvidia-docker

**Comment by gijzelaerr** [comment]
closing this for now, the nvidia docker solution sort of works for now.
